[package]
name = "rustroid"
version = "0.0.1"
authors = ["Sharat M R <cosmosgenius@gmail.com>"]
edition = "2018"
description = "fun cli for android"

[dependencies]
clap = "~2.31.2"
openssl = { version = "0.10", features = ["vendored"] }

